#node version
FROM node:14

# Create app directory
WORKDIR /app

# Install app dependencies
COPY /app/package.json .
RUN npm install


# copy app source code and env file
COPY /app .
COPY ../.env .

# expose port
EXPOSE 5555:5555

# start app
CMD [ "node" , "server.js" ]